apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: np4g6gb63-go 
  janus-idp.io/tekton: np4g6gb63-go
  backstage.io/kubernetes-id: np4g6gb63-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: np4g6gb63-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml